[project]
name = "mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "httpx>=0.28.1",
    "hubspot-api-client>=11.1.0",
    "mcp[cli]>=1.6.0",
    "openai>=1.75.0",
    "supabase>=2.15.0",
]
