
import React from 'react';
import { useParams, Link } from 'react-router-dom';
import { recordings } from '@/lib/dummyData';
import PageHeader from '@/components/layout/PageHeader';
import BottomNavbar from '@/components/layout/BottomNavbar';
import { ArrowLeft, Calendar, Clock, FileText, CheckCircle2, ChevronRight } from 'lucide-react';
import { Button } from '@/components/ui/button';

const RecordingDetail = () => {
  const { id } = useParams<{ id: string }>();
  const recording = recordings.find(r => r.id === id);

  if (!recording) {
    return (
      <div className="mobile-container p-4">
        <Link to="/agent" className="flex items-center text-funnl-primary mb-4">
          <ArrowLeft className="h-4 w-4 mr-1" />
          Back to Recordings
        </Link>
        <div className="text-center p-8">
          <h2 className="text-lg font-semibold text-gray-800">Recording not found</h2>
        </div>
      </div>
    );
  }

  return (
    <div className="mobile-container">
      <PageHeader title={recording.title} subtitle={`${recording.contact.name} - ${recording.contact.company}`} />
      
      <div className="p-4">
        <Link to="/agent" className="flex items-center text-funnl-primary mb-4">
          <ArrowLeft className="h-4 w-4 mr-1" />
          Back to Recordings
        </Link>
        
        <div className="funnl-card mb-6">
          <div className="flex justify-between items-center mb-4">
            <div className="flex items-center text-sm text-gray-600">
              <Calendar className="h-4 w-4 mr-1" />
              <span>{recording.date}</span>
            </div>
            
            <div className="flex items-center text-sm text-gray-600">
              <Clock className="h-4 w-4 mr-1" />
              <span>{recording.duration}</span>
            </div>
          </div>
          
          <div className="bg-gray-50 p-3 rounded-lg mb-4">
            <div className="flex justify-between items-center mb-2">
              <h3 className="text-sm font-medium text-gray-700">Audio Recording</h3>
              <Button variant="ghost" size="sm" className="h-7 text-funnl-primary hover:text-funnl-secondary">
                Download
              </Button>
            </div>
            
            <div className="bg-white rounded-lg p-3 border border-gray-200">
              <div className="w-full bg-gray-200 h-2 rounded-full overflow-hidden">
                <div className="bg-funnl-primary h-full w-3/4 rounded-full"></div>
              </div>
              
              <div className="flex justify-between mt-2 text-xs text-gray-500">
                <span>0:00</span>
                <span>{recording.duration}</span>
              </div>
            </div>
          </div>
        </div>
        
        {recording.summary && (
          <div className="funnl-card mb-6">
            <div className="flex justify-between items-center mb-3">
              <h3 className="text-base font-medium text-gray-800">AI Summary</h3>
              <span className="bg-funnl-soft-purple text-xs px-2 py-1 rounded-full text-funnl-secondary">
                Generated by AI
              </span>
            </div>
            
            <p className="text-sm text-gray-700 mb-4">{recording.summary}</p>
            
            {recording.keyPoints && recording.keyPoints.length > 0 && (
              <div>
                <h4 className="text-sm font-medium text-gray-700 mb-2">Key Points</h4>
                <ul className="list-disc list-inside space-y-1">
                  {recording.keyPoints.map((point, index) => (
                    <li key={index} className="text-sm text-gray-600">{point}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}
        
        {recording.tasks && recording.tasks.length > 0 && (
          <div className="funnl-card mb-6">
            <h3 className="text-base font-medium text-gray-800 mb-3">Generated Tasks</h3>
            
            {recording.tasks.map(task => (
              <div key={task.id} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg mb-2">
                <div className="flex items-start">
                  <CheckCircle2 className="h-5 w-5 text-funnl-primary mr-2 flex-shrink-0" />
                  <div>
                    <h4 className="text-sm font-medium text-gray-800">{task.title}</h4>
                    <p className="text-xs text-gray-600">Due: {task.time}</p>
                  </div>
                </div>
                <Button variant="ghost" size="sm" className="h-7">
                  Add
                </Button>
              </div>
            ))}
          </div>
        )}
        
        {recording.transcription && (
          <div className="funnl-card mb-6">
            <div className="flex justify-between items-center mb-3">
              <h3 className="text-base font-medium text-gray-800">Full Transcription</h3>
              <Button variant="ghost" size="sm" className="h-7 text-funnl-primary hover:text-funnl-secondary">
                <FileText className="h-4 w-4 mr-1" />
                Export
              </Button>
            </div>
            
            <div className="text-sm text-gray-700 bg-gray-50 p-3 rounded-lg max-h-60 overflow-y-auto">
              {recording.transcription}
            </div>
          </div>
        )}
      </div>
      
      <BottomNavbar />
    </div>
  );
};

export default RecordingDetail;
