// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icydzgzveusxrowxismg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljeWR6Z3p2ZXVzeHJvd3hpc21nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDQ1NTEsImV4cCI6MjA1OTY4MDU1MX0.Yqgi4zmh5z8kWgUmNf1mYYqgmCWx4nUD4Z7bM0M2VIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);